### ISSUE TITLE
Won't install if Qlik Sense not installed on default directory

### ISSUE THREAD

**Issue by johnsacco** [eapowertools/qscustomproploader#1]
When trying to run the setup the installer responds that Qlik Sense is not installed on the server. I believe this is because Qlik Sense is installed on a separate drive

**Comment by goldbergjeffrey** [comment]
The installer looks in two places, C and D.  I'm creating a new install now.

Download from here: https://github.com/eapowertools/qscustomproploader/releases/download/0.0.5/setup.exe
